invoices_path = "Invoices/*.xlsx"
pdf_orientation = "P"
pdf_unit = "mm"
pdf_format = "A4"
family_font = "Times"
font_style = 'B'
sheet_name = "Sheet 1"
image_file_name = "pythonhow.png"
image_text = "PythonHow"